changelog:
  categories:
    - title: Product
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Operations
      labels:
        - infra
        - security
        - ci
